### PR TITLE
Support Go Module

### PR DESCRIPTION
**Pull request by zeeshen**
Replace dep with go mod, and keep the vendor directory by `go mod vendor`.

#256

### CODE REVIEW

**Comment by jacksontj** [comment]
Thanks for the PR! This has been an outstanding ask for a while :D Could you add a `make vendor` target in the Makefile with the commands required to update it (don't forget the `.PHONY` line above it to force a run every time people run it :) )

**Comment by zeeshen** [comment]
@jacksontj Thanks for your quick reply. Makefile updated.

**Comment by jacksontj** [comment]
Hmm, seems CI doesn't like that for some reason (from https://travis-ci.org/github/jacksontj/promxy/builds/689949782):

```
$ make test
go test -mod=vendor -v ./...
build flag -mod=vendor only valid when using modules
Makefile:27: recipe for target 'test' failed
make: *** [test] Error 1
The command "make test" exited with 2.
```

**Comment by zeeshen** [comment]
@jacksontj Sorry, forget to check the CI. Fixed.

**Pull request merged**
