### PR TITLE
fix absent() function aggregation

### PR DESCRIPTION
**Pull request by Vladikamira**
it should fix this issue: https://github.com/jacksontj/promxy/issues/496
but I'm not sure that I use correct place in the code to implement this logic

### CODE REVIEW

**Comment by Vladikamira** [comment]
don't understand why it's failed, @jacksontj could you help me with that?
```
➜  promxy git:(absent_func_fix) make test
GO111MODULE=on go test -mod=vendor -tags netgo,builtinassets ./...
?   	github.com/jacksontj/promxy	[no test files]
?   	github.com/jacksontj/promxy/cmd/promxy	[no test files]
?   	github.com/jacksontj/promxy/cmd/remote_write_exporter	[no test files]
ok  	github.com/jacksontj/promxy/pkg/config	1.043s
ok  	github.com/jacksontj/promxy/pkg/logging	0.520s
?   	github.com/jacksontj/promxy/pkg/middleware	[no test files]
ok  	github.com/jacksontj/promxy/pkg/promclient	0.939s
ok  	github.com/jacksontj/promxy/pkg/promhttputil	0.570s
?   	github.com/jacksontj/promxy/pkg/proxyquerier	[no test files]
?   	github.com/jacksontj/promxy/pkg/proxystorage	[no test files]
ok  	github.com/jacksontj/promxy/pkg/remote	12.497s
ok  	github.com/jacksontj/promxy/pkg/server	0.652s
?   	github.com/jacksontj/promxy/pkg/servergroup	[no test files]
ok  	github.com/jacksontj/promxy/test	54.330s
```

**Comment by Vladikamira** [comment]
any update on this?
I guess the reason to not merge it would be that it ruins the current logic of merging, but this PR will align `promxy` merging logic closer to Thanos, which applies aggregation only after pulling all raw metrics first. It would make migration to Promxy from Thanos/Cortex easier.
Maybe we can enable this by feature flag?

**Comment by asand3r** [comment]
Oh, god! It'll solve a lot of my problems! Please, do it as quick as possible. ^_^

**Comment by jacksontj** [comment]
I modified this PR slightly in https://github.com/jacksontj/promxy/pull/565 -- so this issue is resolved on master now, so closing out this PR!

**Pull request closed without merging**
