### PR TITLE
Update prom fork to support parallel walking

### LINKED ISSUE #433: concurrent processing for queries with multiple conditions
Hi! At first thanks for `promxy` as a great product! 👍 

in case of query with multiple conditions and logic operations, seems like Promxy run each of them not in parallel, but one by one:
query example:
```
      (
        not_existed_metric_1 > 0
        and
        not_existed_metric_2 > 2
      )
      and
      (
        not_existed_metric_3 > 0
        and
        not_existed_metric_4 > 0
      )
```
trace log:
```
time="2021-06-04T15:58:59Z" level=debug msg="default (not_existed_metric_1 > 0 and not_existed_metric_2 > 2) and (not_existed_metric_3 > 0 and not_existed_metric_4 > 0) *parser.BinaryExpr"
time="2021-06-04T15:58:59Z" level=debug msg="default (not_existed_metric_1 > 0 and not_existed_metric_2 > 2) *parser.ParenExpr"
time="2021-06-04T15:58:59Z" level=debug msg="default not_existed_metric_1 > 0 and not_existed_metric_2 > 2 *parser.BinaryExpr"
time="2021-06-04T15:58:59Z" level=debug msg="default not_existed_metric_1 > 0 *parser.BinaryExpr"
time="2021-06-04T15:58:59Z" level=debug msg="VectorSelector: not_existed_metric_1"
time="2021-06-04T15:58:59Z" level=debug msg="http://vmselect-k8s-tst:80/select/0/prometheus" api=QueryRange query=not_existed_metric_1 r="{2021-06-04 14:58:59.883 +0000 UTC 2021-06-04 15:58:59.883 +0000 UTC 14s}"
time="2021-06-04T15:59:00Z" level=trace msg="http://vmselect-k8s-tst:80/select/0/prometheus" api=QueryRange error="<nil>" query=not_existed_metric_1 r="{2021-06-04 14:58:59.883 +0000 UTC 2021-06-04 15:58:59.883 +0000 UTC 14s}" took=139.26757ms value= warnings="[]"
time="2021-06-04T15:59:00Z" level=debug msg="default not_existed_metric_2 > 2 *parser.BinaryExpr"
time="2021-06-04T15:59:00Z" level=debug msg="VectorSelector: not_existed_metric_2"
time="2021-06-04T15:59:00Z" level=debug msg="http://vmselect-k8s-tst:80/select/0/prometheus" api=QueryRange query=not_existed_metric_2 r="{2021-06-04 14:58:59.883 +0000 UTC 2021-06-04 15:58:59.883 +0000 UTC 14s}"
time="2021-06-04T15:59:00Z" level=trace msg="http://vmselect-k8s-tst:80/select/0/prometheus" api=QueryRange error="<nil>" query=not_existed_metric_2 r="{2021-06-04 14:58:59.883 +0000 UTC 2021-06-04 15:58:59.883 +0000 UTC 14s}" took=136.44413ms value= warnings="[]"
time="2021-06-04T15:59:00Z" level=debug msg="default (not_existed_metric_3 > 0 and not_existed_metric_4 > 0) *parser.ParenExpr"
time="2021-06-04T15:59:00Z" level=debug msg="default not_existed_metric_3 > 0 and not_existed_metric_4 > 0 *parser.BinaryExpr"
time="2021-06-04T15:59:00Z" level=debug msg="default not_existed_metric_3 > 0 *parser.BinaryExpr"
time="2021-06-04T15:59:00Z" level=debug msg="VectorSelector: not_existed_metric_3"
time="2021-06-04T15:59:00Z" level=debug msg="http://vmselect-k8s-tst:80/select/0/prometheus" api=QueryRange query=not_existed_metric_3 r="{2021-06-04 14:58:59.883 +0000 UTC 2021-06-04 15:58:59.883 +0000 UTC 14s}"
time="2021-06-04T15:59:00Z" level=trace msg="http://vmselect-k8s-tst:80/select/0/prometheus" api=QueryRange error="<nil>" query=not_existed_metric_3 r="{2021-06-04 14:58:59.883 +0000 UTC 2021-06-04 15:58:59.883 +0000 UTC 14s}" took=135.749946ms value= warnings="[]"
time="2021-06-04T15:59:00Z" level=debug msg="default not_existed_metric_4 > 0 *parser.BinaryExpr"
time="2021-06-04T15:59:00Z" level=debug msg="VectorSelector: not_existed_metric_4"
time="2021-06-04T15:59:00Z" level=debug msg="http://vmselect-k8s-tst:80/select/0/prometheus" api=QueryRange query=not_existed_metric_4 r="{2021-06-04 14:58:59.883 +0000 UTC 2021-06-04 15:58:59.883 +0000 UTC 14s}"
time="2021-06-04T15:59:00Z" level=trace msg="http://vmselect-k8s-tst:80/select/0/prometheus" api=QueryRange error="<nil>" query=not_existed_metric_4 r="{2021-06-04 14:58:59.883 +0000 UTC 2021-06-04 15:58:59.883 +0000 UTC 14s}" took=135.637795ms value= warnings="[]"
10.30.164.10 - - [04/Jun/2021 15:59:00] "GET /api/v1/query_range HTTP/1.1 200 87" 0.550104 query=++++++%28%0A++++++++not_existed_metric_1+%3E+0%0A++++++++and%0A++++++++not_existed_metric_2+%3E+2%0A++++++%29%0A++++++and%0A++++++%28%0A++++++++not_existed_metric_3+%3E+0%0A++++++++and%0A++++++++not_existed_metric_4+%3E+0%0A++++++%29&start=1622818739
```

In our case we have some backends (VictoriaMetrics) located on another continent so each of request RTT is ~`150ms` and if there are multiple of them we got summarised response time. Take a look to the screenshot:
Screenshot 2021-06-04 at 17 59 19

Is it possible to make Parallel execution of them, not sequentially ?

Seems like Promxy

### LINKED ISSUE #461: Parallel ast.Walk has errors with BinaryExpr
I was digging some more into https://github.com/jacksontj/promxy/issues/451 and it seems that there is some issue with parallel execution of ast.Walk specifically for BinaryExprs. Unfortunately I have no good lead at this point on *what* that may be but that was where I seemed to find an issue. Creating this to track a longer-term fix. For now I'll revert the parallel execution in the latest prom fork which I'm working to upgrade to (https://github.com/jacksontj/promxy/pull/460)

### PR DESCRIPTION
**Pull request by jacksontj**
Fixes #461
Fixes #433

### CODE REVIEW

**Comment by jacksontj** [comment]
@sagor999 if you have some time, could you try out this build to see if this solves your issues from #451

**Comment by sagor999** [comment]
Just to confirm, I am running this version in our environment. Going to wait 48 hours to see if it will trigger or not.

**Comment by jacksontj** [comment]
@sagor999 to confirm; you don't get this on current master (same thing just without parallel walking); If so then I'll probably just have to hack up another build; your bug is hard to repro!

**Comment by sagor999** [comment]
@jacksontj I was getting it on 0.0.72, but right now going to switch to 0.0.73 and will let you now if I will get it on that version or not (I suspect it shouldn't happen).

**Comment by jacksontj** [comment]
@sagor999 assuming we can't repro on 0.0.73; I pushed a new branch to `no_recover` which has `-race` enabled; as this really seems like some race condition. What that flag will do is print out when there are potential race conditions; so my hope is we can catch it with that.

**Comment by jacksontj** [comment]
@sagor999 I assume no error/crash on 0.0.73; assuming that is accurate any chance to run that updated `no_recover` build?

**Comment by sagor999** [comment]
@jacksontj cannot build container on that branch.
```
Step 7/16 : RUN cd /go/src/github.com/jacksontj/promxy/cmd/promxy && CGO_ENABLED=0 go build -race -mod=vendor -tags netgo,builtinassets
 ---> Running in d38905ecb368
go build: -race requires cgo; enable cgo by setting CGO_ENABLED=1
```
Setting CGO_ENABLED=1 results in:
```
Step 7/16 : RUN cd /go/src/github.com/jacksontj/promxy/cmd/promxy && CGO_ENABLED=1 go build -race -mod=vendor -tags netgo,builtinassets
 ---> Running in 66baed707b83
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
```
Probably it needs a different builder container?

**Comment by jacksontj** [comment]
@sagor999 I just changed the builder and run base to debian which seems to build

**Comment by sagor999** [comment]
Ok, it is running now. Will let you know when I catch the error. Might take a day or so. Doesn't happen very often :(

**Comment by jacksontj** [comment]
Thanks for running this; Unfortunately we don't have a more reliable repro case :/ 

One thing to point out; with the `-race` flag it will print out potential race conditions even if it didn't cause a panic/error. So it would probably be worth checking intermittently for any log output from that.

**Comment by sagor999** [comment]
Hm. So far there were no repro of that bug and no output in container that would print anything about possible race condition. All I see in logs are just GET and POST requests that are logged. Nothing else. :thinking: 
Could it be that adding `-race` somehow made it so that you can no longer repro the bug?

**Comment by jacksontj** [comment]
That is definitely possible (race adds additional tracking internally which can slow it down some). Unfortunately that'll make it all the harder to track down... I'll have to think on this for a bit. Basically I think we'll have to resort to checking for the condition in a few places in the code to guess where it is occurring (which will be a pain), I'll have to see if I can come up with something better :/

**Comment by Vladikamira** [comment]
any update on this? 
We process a lot of complex queries on `promxy` and stuck on version `v0.0.71` because of performance improvements on such queries

**Comment by Vladikamira** [comment]
Is it possible to add some flag to be able to switch between parallel and sequential walking?

**Pull request closed without merging**
