### PR TITLE
A new wrapper client that rewrites the query with replacement labels

### PR DESCRIPTION
**Pull request by xujiaxj**
This introduces a new setting in the config

```
      label_replaces:
        asserts_env: env
```

When this is present, promxy will rewrite the query in a way all the `asserts_env` in the query will be replaced with `env` label, so query `up{asserts_env="dev"` will become `up{env="dev"}`.

In the returned result, a new label `asserts_env` will be included with the value the same as `env` label. `env` label is still kept in the result.

### CODE REVIEW

**Comment by xujiaxj** [comment]
Just have it here for feedbacks, not in a hurry to merge.

**Comment by jacksontj** [comment]
I definitely like the idea of this. A few points of feedback (in no particular order):

- `label_replaces` is a bit of a confusing name; given that `labels` is what adds labels; maybe this should be `labels_replace`? This is especially confusing since the `relabel_config` in prometheus is sort-of this and in promxy its different.
- I don't see any tests in the PR; I would highly recommend some tests to cover the relabeling. Both to make sure it works (and continues to work) but also to showcase the behavior.
- Changes to `vendor` should be made upstream and pulled in. I see you have a change in promql; so if that is upstream we can merge that into the fork.

**Comment by xujiaxj** [comment]
Thx for the feedback, will get back to rework on that.

**Comment by xujiaxj** [comment]
@jacksontj I noticed that the latest `metric_relabel_configs` feature had included this idea. Many thanks!

**Pull request closed without merging**
